### ISSUE TITLE
Auto-accepted quests give mood debuff on expiration

### ISSUE THREAD

**Issue by gyurka66** [SirMashedPotato/QuesterMeme#1]
For example faction huting/mining/lodging raiding targets.

This is a problem because in many cases you are forced to choose between raiding a friendly faction or taking the debuff.

**Comment by SirMashedPotato** [comment]
[Added a new version of Honourable in 1.0.1.](https://github.com/SirMashedPotato/QuesterMeme/commit/245b76199c6f533e60293248024969fd92df8166)

**Comment by SirMashedPotato** [comment]
[Added a new version of Honourable in 1.0.1.](https://github.com/SirMashedPotato/QuesterMeme/commit/245b76199c6f533e60293248024969fd92df8166)

**Comment by SirMashedPotato** [comment]
And actually closing it as completed.
